version: "3"
name: "docker-volumes-demo"

services:
  dv-app1:
    image: dv-app:latest
    ports:
      - "5001:5000"
    volumes:
      - type: volume
        source: my-shared-volume
        target: /data
  dv-app2:
    image: dv-app2:latest
    ports:
      - "5002:5000"
    volumes:
      - type: volume
        source: my-shared-volume
        target: /data
        read_only: true

volumes:
  my-shared-volume: