version: "3"
name: "docker-volumes-demo"

services:
  dv-app1:
    image: dv-app:latest
    ports:
      - "5001:5000"
    volumes:
      - my-shared-volume:/data
  dv-app2:
    image: dv-app2:latest
    ports:
      - "5002:5000"
    volumes:
      - my-shared-volume:/data

volumes:
  my-shared-volume: